# Generated by Django 6.0.5 on 2026-05-26 20:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='juegoResponsabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario', models.DecimalField(decimal_places=3, default=Decimal('1000.000'), max_digits=10)),
                ('limite_semanal', models.DecimalField(decimal_places=3, default=Decimal('7000.000'), max_digits=10)),
                ('limite_mensual', models.DecimalField(decimal_places=3, default=Decimal('15000.000'), max_digits=10)),
                ('autoexclusion_fecha_fin', models.DateField(blank=True, null=True)),
                ('autoexclusion_indefinida', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
