# Generated by Django 6.0.5 on 2026-05-26 20:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPP', '0002_juegoresponsabe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegoresponsabe',
            name='limite_diario',
            field=models.DecimalField(decimal_places=4, default=Decimal('1000.000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='juegoresponsabe',
            name='limite_mensual',
            field=models.DecimalField(decimal_places=4, default=Decimal('15000.000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='juegoresponsabe',
            name='limite_semanal',
            field=models.DecimalField(decimal_places=4, default=Decimal('7000.000'), max_digits=18),
        ),
    ]
