# Generated by Django 6.0.5 on 2026-05-26 21:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPP', '0003_alter_juegoresponsabe_limite_diario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegoresponsabe',
            name='ultima_modificacion_limite',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='juegoresponsabe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
