# Generated by Django 6.0.4 on 2026-05-28 07:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
                ('visitante', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En Vivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('anulado', 'Anulado')], default='programado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1x2', 'Gana local (1) / Empate (X) / Gana visitante (2)')], default='1x2', max_length=20)),
                ('margen_operador', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercados', to='eventoAPP.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Gana local'), ('X', 'Empate'), ('2', 'Gana visitante')], max_length=2)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='eventoAPP.mercado')),
            ],
        ),
    ]
