# Generated by Django 6.0.4 on 2026-05-28 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventoAPP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApuestaMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('combinada', 'Combinada')], default='simple', max_length=20)),
                ('estado', models.CharField(choices=[('accepted', 'Aceptada'), ('won', 'Ganada'), ('loast', 'Perdida'), ('cashed_out', 'Cerrada Anticipadamente')], default='accepted', max_length=20)),
                ('monto_apostado', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cuota_total', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ganancia_potencial', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fecha_apuesta', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApuestaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuato_aplicada', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('won', 'Ganada'), ('lost', 'Perdida'), ('void', 'Anulada/Devuelta')], default='pending', max_length=20)),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas_detalle', to='eventoAPP.seleccion')),
                ('apuesta_maestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='apuestaAPP.apuestamaestra')),
            ],
        ),
    ]
